import "~/styles/globals.css";

import Image from "next/image";
import { inter, playfair_display } from "~/app/fonts";
import { ReactNode } from "react";

export const metadata = {
  title: "Dni otware Uniwersytetu Zielonogórskiego",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const navElements = [
  {
    title: "Uczelnia",
    iconPath: "/uz-logo.png",
    width: 100,
    height: 60,
    url: "https://uz.zgora.pl/",
  },
  {
    title: "Rekrutacja",
    iconPath: "/recrutation-icon.png",
    url: "https://rekrutacja.uz.zgora.pl/"
  },
  {
    title: "Mapa wydarzenia",
    iconPath: "/map-icon.png",
    url: "#"
  }
]

function Nav () {
  return (
      <nav>
        <h1 className={ `${playfair_display.className} text-4xl lg:text-5xl font-bold text-center my-8` }>Dni Otwarte Uniwersytetu Zielonogórskiego</h1>
        <div className="flex flex-wrap flex-row justify-center w-full mx-2">
          { navElements.map( ( { title, iconPath, width, height, url }, index ) => (
              <div key={index+1} className="flex flex-col justify-between items-center text-center min-w-24 w-1/4 p-5 mx-3 shadow-md rounded-lg hover:bg-gray-300">
                <Image width={width ? width : 64} height={height ? height : 64} className="w-16 h-16" src={iconPath} alt={title}></Image>
                <h4>{title}</h4>
              </div>
          ) ) }
        </div>
      </nav>
  )
}

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="pl">
    <body className="font-sans">
      <div className={ `flex flex-col items-center justify-center min-h-screen max-w-5xl mx-auto ${ inter.className }` }>
        <Nav />
        { children }
      </div>
    </body>
    </html>
);
}
