import "~/styles/globals.css";
import { inter, playfair_display } from "~/styles/fonts";
import { type ReactNode } from "react";
import { format } from "date-fns";
import { pl } from "date-fns/locale";
import { db } from "~/server/db";
import { pageDetails } from "~/server/db/schema";

export const metadata = {
  title: "Dni otwarte na UZ",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  const mainSettings = await db.select().from(pageDetails);

  let values;

  if (mainSettings.length === 0) {
    values = {
      date: new Date(),
      title: "Brak informacji",
      organizer: "Brak informacji",
    };
  } else {
    values = {
      date:
        mainSettings[0]?.date === null
          ? new Date()
          : (mainSettings[0]?.date as Date),
      title:
        mainSettings[0]?.title === null
          ? "Brak informacji"
          : (mainSettings[0]?.title as string),
      organizer:
        mainSettings[0]?.organizer === null
          ? "Brak informacji"
          : (mainSettings[0]?.organizer as string),
    };
  }

  return (
    <html lang="pl">
      <body className="font-sans">
        <h1
          className={`${playfair_display.className} my-8 text-center text-4xl font-bold lg:text-5xl`}
        >
          {values.title}
        </h1>
        <h3
          className={`${playfair_display.className} text-center text-xl font-bold lg:text-2xl`}
        >
          {values.organizer}
        </h3>
        <h3
          className={`${playfair_display.className} text-center text-xl font-bold lg:text-2xl`}
        >
          {format(values.date, "do, MMMM yyyy", { locale: pl })}
        </h3>
        <main
          className={`mx-auto flex max-w-5xl flex-col items-center justify-center ${inter.className}`}
        >
          {children}
        </main>
      </body>
    </html>
  );
}
